### ISSUE TITLE
Feature: Expose an API to interact with MoneroTipBot

### ISSUE THREAD

**Issue by omani** [omani/go-telegram-monerotipbot#2]
Currently MoneroTipBot is not accessable/usable through another bot since Telegram does not allow to talk between bots.

But developers might want to build their own services while using the MoneroTipBot as a backend for their (Monero) apps on Telegram.

*Proposal*:
Build an API for one or more or all commands of MoneroTipBot and enable interaction with a user's **own** wallet through this exposed API endpoint.

*Use case*:
A user can access his/her own wallet through his/her own bot on Telegram to offer services (eg. quiz bot, giveaway bots, rating bots, gaming bots, etc.) and use implemented commands through the bot and thus automate things.

Rate this feature proposal by giving thumbs up or down on this OP (opening post).
Or a +1 or -1 if you like to comment.

When this proposal gets enough thumbs up or +1, it will be implemented.

**Comment by Endogen** [comment]
Good idea. And you are thinking about an endpoint for everyone to use, not just for other Telegram bots right?

JSON please :-)

**Comment by omani** [comment]
> Good idea. And you are thinking about an endpoint for everyone to use, not just for other Telegram bots right?

yes. everyone as in: bots or users (eg. via MTProto)

> JSON please :-)

yes

**Comment by Endogen** [comment]
Initially i thought about an API that is also accessible from outside of Telegram but quickly realized that it wouldn't work of course.

**Comment by omani** [comment]
it will be publicly available, that means outside from Telegram as well so actually it is not restricted or bound to Telegram only.

**Comment by Endogen** [comment]
Yes but you will have to use MTProto and that's what i initially didn't get

**Comment by omani** [comment]
due to no public interest I will close this issue and dismiss this feature.
