### ISSUE TITLE
Issues with tipping/sending/receiving

### ISSUE THREAD

**Issue by lh1008** [omani/go-telegram-monerotipbot#6]
Hello everyone,

Since last update the bot has not been able to send, receive, or tip but the bot is still active. You can still interact with the bot. Can updates be pushed to the repository in order to update the bot to the latest Oxygen Orion v0.17.1.1?

Thank you :)

**Comment by omani** [comment]
hi @lh1008 ,
thanks for the message. this was an issue on the remote node side. it took a while but eventually the remote node was updated to the latest version of the monero core software. there was no need to do anything on our side.

happy tipping! :)
